services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: panda-site
    environment:
      - DOMAIN=pandoral.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certs:/etc/nginx/certs
      - ./nginx/auth/dash.htpasswd:/etc/nginx/auth/dash.htpasswd:ro
    networks:
      - default
      - proxy_net
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: panda-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h;
      done"
    restart: unless-stopped

networks:
  proxy_net:
    external: true
